/**
 * Achievement Definitions
 */

import { Achievement, AchievementCategory, AchievementTier } from './types';

export const ACHIEVEMENTS: Achievement[] = [
  // Exploration achievements
  {
    id: 'exp_first_view',
    code: 'FIRST_VIEW',
    name: 'First Steps',
    description: 'View your first affiliate program',
    icon: '👀',
    points: 10,
    category: 'exploration',
    tier: 'bronze',
    requirement: 1,
  },
  {
    id: 'exp_explorer_10',
    code: 'EXPLORER_10',
    name: 'Curious Explorer',
    description: 'View 10 different programs',
    icon: '🔍',
    points: 25,
    category: 'exploration',
    tier: 'bronze',
    requirement: 10,
  },
  {
    id: 'exp_explorer_50',
    code: 'EXPLORER_50',
    name: 'Program Hunter',
    description: 'View 50 different programs',
    icon: '🎯',
    points: 100,
    category: 'exploration',
    tier: 'silver',
    requirement: 50,
  },
  {
    id: 'exp_explorer_100',
    code: 'EXPLORER_100',
    name: 'Affiliate Expert',
    description: 'View 100 different programs',
    icon: '🏆',
    points: 250,
    category: 'exploration',
    tier: 'gold',
    requirement: 100,
  },
  {
    id: 'exp_explorer_500',
    code: 'EXPLORER_500',
    name: 'Market Master',
    description: 'View 500 different programs',
    icon: '👑',
    points: 1000,
    category: 'exploration',
    tier: 'platinum',
    requirement: 500,
  },

  // Engagement achievements
  {
    id: 'eng_first_click',
    code: 'FIRST_CLICK',
    name: 'Taking Action',
    description: 'Click through to your first program',
    icon: '👆',
    points: 15,
    category: 'engagement',
    tier: 'bronze',
    requirement: 1,
  },
  {
    id: 'eng_clicker_10',
    code: 'CLICKER_10',
    name: 'Active User',
    description: 'Click through to 10 programs',
    icon: '🖱️',
    points: 50,
    category: 'engagement',
    tier: 'bronze',
    requirement: 10,
  },
  {
    id: 'eng_clicker_50',
    code: 'CLICKER_50',
    name: 'Deal Seeker',
    description: 'Click through to 50 programs',
    icon: '💼',
    points: 150,
    category: 'engagement',
    tier: 'silver',
    requirement: 50,
  },
  {
    id: 'eng_first_review',
    code: 'FIRST_REVIEW',
    name: 'Voice Heard',
    description: 'Write your first review',
    icon: '✍️',
    points: 50,
    category: 'engagement',
    tier: 'bronze',
    requirement: 1,
  },
  {
    id: 'eng_reviewer_5',
    code: 'REVIEWER_5',
    name: 'Helpful Reviewer',
    description: 'Write 5 reviews',
    icon: '📝',
    points: 150,
    category: 'engagement',
    tier: 'silver',
    requirement: 5,
  },
  {
    id: 'eng_reviewer_20',
    code: 'REVIEWER_20',
    name: 'Review Champion',
    description: 'Write 20 reviews',
    icon: '🌟',
    points: 500,
    category: 'engagement',
    tier: 'gold',
    requirement: 20,
  },
  {
    id: 'eng_helpful_10',
    code: 'HELPFUL_10',
    name: 'Community Helper',
    description: 'Receive 10 helpful votes on your reviews',
    icon: '👍',
    points: 100,
    category: 'engagement',
    tier: 'silver',
    requirement: 10,
  },
  {
    id: 'eng_helpful_50',
    code: 'HELPFUL_50',
    name: 'Trusted Voice',
    description: 'Receive 50 helpful votes on your reviews',
    icon: '⭐',
    points: 300,
    category: 'engagement',
    tier: 'gold',
    requirement: 50,
  },

  // Social achievements
  {
    id: 'soc_first_referral',
    code: 'FIRST_REFERRAL',
    name: 'Connector',
    description: 'Refer your first friend',
    icon: '🤝',
    points: 100,
    category: 'social',
    tier: 'bronze',
    requirement: 1,
  },
  {
    id: 'soc_referral_5',
    code: 'REFERRAL_5',
    name: 'Influencer',
    description: 'Refer 5 friends',
    icon: '📣',
    points: 300,
    category: 'social',
    tier: 'silver',
    requirement: 5,
  },
  {
    id: 'soc_referral_25',
    code: 'REFERRAL_25',
    name: 'Ambassador',
    description: 'Refer 25 friends',
    icon: '🏅',
    points: 1000,
    category: 'social',
    tier: 'gold',
    requirement: 25,
  },
  {
    id: 'soc_first_share',
    code: 'FIRST_SHARE',
    name: 'Sharer',
    description: 'Share a program for the first time',
    icon: '📤',
    points: 20,
    category: 'social',
    tier: 'bronze',
    requirement: 1,
  },

  // Loyalty achievements
  {
    id: 'loy_first_login',
    code: 'FIRST_LOGIN',
    name: 'Welcome!',
    description: 'Complete your first login',
    icon: '🎉',
    points: 10,
    category: 'loyalty',
    tier: 'bronze',
    requirement: 1,
  },
  {
    id: 'loy_streak_3',
    code: 'STREAK_3',
    name: 'Consistent',
    description: 'Log in 3 days in a row',
    icon: '🔥',
    points: 30,
    category: 'loyalty',
    tier: 'bronze',
    requirement: 3,
  },
  {
    id: 'loy_streak_7',
    code: 'STREAK_7',
    name: 'Dedicated',
    description: 'Log in 7 days in a row',
    icon: '💪',
    points: 100,
    category: 'loyalty',
    tier: 'silver',
    requirement: 7,
  },
  {
    id: 'loy_streak_30',
    code: 'STREAK_30',
    name: 'Unstoppable',
    description: 'Log in 30 days in a row',
    icon: '⚡',
    points: 500,
    category: 'loyalty',
    tier: 'gold',
    requirement: 30,
  },
  {
    id: 'loy_streak_100',
    code: 'STREAK_100',
    name: 'Legendary Streak',
    description: 'Log in 100 days in a row',
    icon: '🌈',
    points: 2000,
    category: 'loyalty',
    tier: 'platinum',
    requirement: 100,
  },

  // Milestone achievements
  {
    id: 'mil_level_5',
    code: 'LEVEL_5',
    name: 'Rising Star',
    description: 'Reach level 5',
    icon: '⭐',
    points: 100,
    category: 'milestone',
    tier: 'bronze',
    requirement: 5,
  },
  {
    id: 'mil_level_10',
    code: 'LEVEL_10',
    name: 'Established',
    description: 'Reach level 10',
    icon: '🌟',
    points: 250,
    category: 'milestone',
    tier: 'silver',
    requirement: 10,
  },
  {
    id: 'mil_level_15',
    code: 'LEVEL_15',
    name: 'Veteran',
    description: 'Reach level 15',
    icon: '💎',
    points: 500,
    category: 'milestone',
    tier: 'gold',
    requirement: 15,
  },
  {
    id: 'mil_level_20',
    code: 'LEVEL_20',
    name: 'Ultimate',
    description: 'Reach the maximum level',
    icon: '👑',
    points: 2000,
    category: 'milestone',
    tier: 'diamond',
    requirement: 20,
  },
  {
    id: 'mil_points_1000',
    code: 'POINTS_1000',
    name: 'First Milestone',
    description: 'Earn 1,000 total points',
    icon: '🎯',
    points: 50,
    category: 'milestone',
    tier: 'bronze',
    requirement: 1000,
  },
  {
    id: 'mil_points_10000',
    code: 'POINTS_10000',
    name: 'Point Master',
    description: 'Earn 10,000 total points',
    icon: '🏆',
    points: 200,
    category: 'milestone',
    tier: 'gold',
    requirement: 10000,
  },

  // Secret achievements
  {
    id: 'sec_night_owl',
    code: 'NIGHT_OWL',
    name: 'Night Owl',
    description: 'Browse programs between midnight and 4 AM',
    icon: '🦉',
    points: 50,
    category: 'engagement',
    tier: 'bronze',
    requirement: 1,
    isSecret: true,
  },
  {
    id: 'sec_early_bird',
    code: 'EARLY_BIRD',
    name: 'Early Bird',
    description: 'Be one of the first 100 users',
    icon: '🐦',
    points: 500,
    category: 'milestone',
    tier: 'gold',
    requirement: 1,
    isSecret: true,
  },
];

export function getAchievementsByCategory(category: AchievementCategory): Achievement[] {
  return ACHIEVEMENTS.filter((a) => a.category === category && !a.isSecret);
}

export function getAchievementById(id: string): Achievement | undefined {
  return ACHIEVEMENTS.find((a) => a.id === id);
}

export function getAchievementByCode(code: string): Achievement | undefined {
  return ACHIEVEMENTS.find((a) => a.code === code);
}

export function getTierColor(tier: AchievementTier): string {
  const colors: Record<AchievementTier, string> = {
    bronze: '#CD7F32',
    silver: '#C0C0C0',
    gold: '#FFD700',
    platinum: '#E5E4E2',
    diamond: '#B9F2FF',
  };
  return colors[tier];
}

export function getTierBgClass(tier: AchievementTier): string {
  const classes: Record<AchievementTier, string> = {
    bronze: 'bg-orange-100 dark:bg-orange-900 border-orange-300',
    silver: 'bg-gray-100 dark:bg-gray-700 border-gray-300',
    gold: 'bg-yellow-100 dark:bg-yellow-900 border-yellow-300',
    platinum: 'bg-purple-100 dark:bg-purple-900 border-purple-300',
    diamond: 'bg-cyan-100 dark:bg-cyan-900 border-cyan-300',
  };
  return classes[tier];
}
